#
# Copyright (c) 2025 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: 8080
  host: 0.0.0.0

# OCI Auth related properties
# https://github.com/helidon-io/helidon/blob/main/integrations/oci/oci/README.md
helidon.oci:
  region: us-chicago-1
  authentication:
    config-file:
      profile: "token"

# OCI GenAI related properties
oci:
  genai:
    # https://docs.oracle.com/en-us/iaas/tools/java/3.53.1/com/oracle/bmc/Region.html
    # ENDPOINT will be set as: "https://inference.generativeai.%s.oci.oraclecloud.com"
    region: us-chicago-1
    # Please use the compartmentId that has policies grant permissions for using Generative AI Service
    compartment.id: ocid1.compartment.oc1..aaaaaaaaiwoctrgf6w6rtq7az62fabscwgzbax2iepwu2qlub5qzcvabn5wa
    # meta.llama-3.1-70b-instruct
    chat.model.id: ocid1.generativeaimodel.oc1.us-chicago-1.aaaaaaaajvzlykcfhewzdlwnphkuowjuobt53bi5eyhok4pazitzd4w7t4eq
    # cohere.embed-english-light-v3.0
    embedding.model.id: ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceya6fw6mqgi2mcmehwvd7h2ysqe25rbhprgclypiyh46wra



