#
# Copyright (c) 2025 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Microprofile server properties
server.port=8080
server.host=0.0.0.0

# OCI Auth related properties
# https://helidon.io/docs/latest/apidocs/io.helidon.integrations.oci.sdk.cdi/io/helidon/integrations/oci/sdk/cdi/OciExtension.html
# config,config-file,session-token-config-file,session-token-builder,instance-principals,resource-principal,oke-workload-identity
oci.auth-strategies=session-token-config-file
oci.config.profile=<name of the session-token auth profile in your default oci configuration file>

# OCI GenAI related properties
# https://docs.oracle.com/en-us/iaas/tools/java/3.53.1/com/oracle/bmc/Region.html
# ENDPOINT will be set as: "https://inference.generativeai.%s.oci.oraclecloud.com"
oci.genai.region=<your subscribed region e.g. us-chicago-1>

# Please use the compartmentId that has policies grant permissions for using Generative AI Service
oci.genai.compartment.id=<ocid of your compartment where model is running>

# For meta.llama-3.1-70b-instruct OCID is
# ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceyaiir6nnhmlgwvh37dr2mvragxzszqmz3hok52pcgmpqta
oci.genai.chat.model.id=<ocid of LLM that you want to use>
# For cohere.embed-english-light-v3.0 OCID is
# ocid1.generativeaimodel.oc1.us-chicago-1.amaaaaaask7dceya6fw6mqgi2mcmehwvd7h2ysqe25rbhprgclypiyh46wra
oci.genai.embedding.model.id=<ocid of embedding model that you want to use>
