/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.examples.declarative.data.jdbc.model;

import java.util.List;
import java.util.Optional;

import io.helidon.data.Data;
import io.helidon.data.jdbc.Jdbc;

/**
 * Defines the declarative JDBC queries used by the Pokemon example.
 * <p>
 * The {@link Jdbc.RowMapper} marker selects the {@code JdbcClient.RowMapper<Pokemon>} service that maps each joined
 * row to a nested {@link Pokemon} model.
 */
@Data.Repository
@Data.Provider("jdbc")
public interface PokemonRepository extends PokemonLookup {

    /**
     * Retrieves all Pokemon ordered by name.
     *
     * @return all Pokemon in name order
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            ORDER BY p.NAME
            """)
    @Jdbc.RowMapper
    List<Pokemon> listOrderByName();

    /**
     * Retrieves Pokemon having the requested type name.
     *
     * @param typeName type name
     * @return matching Pokemon in name order
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            WHERE t.NAME = :typeName
            ORDER BY p.NAME
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper
    List<Pokemon> listByTypeName(String typeName);

    /**
     * Retrieves Pokemon whose name or type matches one search term.
     * <p>
     * The repeated named marker binds the same argument to both JDBC positions.
     *
     * @param term Pokemon or type name
     * @return matching Pokemon in name order
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            WHERE p.NAME = :term OR t.NAME = :term
            ORDER BY p.NAME
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper
    List<Pokemon> listByNameOrType(String term);

    /**
     * Retrieves a Pokemon by name with an explicitly selected mapper.
     * <p>
     * The class value selects {@link PokemonAlternateRowMapper} instead of relying on service weight.
     *
     * @param name Pokemon name
     * @return Pokemon mapped by the alternate mapper, or an empty optional when it does not exist
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            WHERE p.NAME = :name
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper(PokemonAlternateRowMapper.class)
    Optional<Pokemon> findByNameWithAlternateMapper(String name);

    /**
     * Retrieves a Pokemon by type and name.
     * <p>
     * Parameter order matches the positional parameters in the SQL statement.
     *
     * @param typeName type name for the first SQL parameter
     * @param name Pokemon name for the second SQL parameter
     * @return matching Pokemon, or an empty optional when it does not exist
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            WHERE t.NAME = ? AND p.NAME = ?
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper
    Optional<Pokemon> findByTypeAndName(String typeName, String name);

    /**
     * Inserts a Pokemon and returns the identifier generated by the database.
     *
     * @param name Pokemon name
     * @param typeId type identifier
     * @return generated Pokemon identifier
     */
    @Jdbc.Statement("INSERT INTO POKEMON (NAME, TYPE_ID) VALUES (:name, :typeId)")
    @Jdbc.GeneratedKeys("ID")
    int insert(String name, int typeId);

    /**
     * Counts all Pokemon rows.
     * <p>
     * The explicit query type distinguishes a scalar count from an update count.
     *
     * @return number of Pokemon rows
     */
    @Jdbc.Statement("SELECT COUNT(*) FROM POKEMON")
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    long count();

    /**
     * Deletes a Pokemon by identifier.
     *
     * @param id Pokemon identifier
     * @return number of deleted rows
     */
    @Jdbc.Statement("DELETE FROM POKEMON WHERE ID = :id")
    @Jdbc.Execution(Jdbc.ExecutionType.UPDATE)
    long deleteById(int id);
}
