/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.examples.declarative.data.jdbc.model;

import java.util.List;
import java.util.Optional;

import io.helidon.data.Data;
import io.helidon.data.jdbc.Jdbc;

/**
 * Declarative JDBC repository for the Pokémon operations used by the example.
 * <p>
 * JDBC repositories declare their SQL and execution types explicitly. The {@link Jdbc.RowMapper} marker selects the
 * {@code JdbcClient.RowMapper<Pokemon>} service that maps each joined row to the nested {@link Pokemon} model.
 */
@Data.Repository
@Data.Provider("jdbc")
public interface PokemonRepository {

    /**
     * Retrieves all Pokémon ordered by name.
     *
     * @return all Pokémon in name order
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            ORDER BY p.NAME
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper
    List<Pokemon> listOrderByName();

    /**
     * Retrieves Pokémon having the requested type name.
     *
     * @param typeName type name
     * @return matching Pokémon in name order
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            WHERE t.NAME = :typeName
            ORDER BY p.NAME
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper
    List<Pokemon> listByType_Name(String typeName);

    /**
     * Retrieves a Pokémon by name.
     *
     * @param name Pokémon name
     * @return matching Pokémon, or an empty optional when it does not exist
     */
    @Jdbc.Statement("""
            SELECT p.ID AS id,
                   p.NAME AS name,
                   p.TYPE_ID AS typeId,
                   t.NAME AS typeName
            FROM POKEMON p
            JOIN TYPE t ON t.ID = p.TYPE_ID
            WHERE p.NAME = :name
            """)
    @Jdbc.Execution(Jdbc.ExecutionType.QUERY)
    @Jdbc.RowMapper
    Optional<Pokemon> findByName(String name);

    /**
     * Inserts a Pokémon and returns the identifier generated by MySQL.
     *
     * @param name Pokémon name
     * @param typeId type identifier
     * @return generated Pokémon identifier
     */
    @Jdbc.Statement("INSERT INTO POKEMON (NAME, TYPE_ID) VALUES (:name, :typeId)")
    @Jdbc.Execution(Jdbc.ExecutionType.UPDATE)
    @Jdbc.GeneratedKeys("ID")
    int insert(String name, int typeId);

    /**
     * Deletes a Pokémon by identifier.
     *
     * @param id Pokémon identifier
     * @return number of deleted rows
     */
    @Jdbc.Statement("DELETE FROM POKEMON WHERE ID = :id")
    @Jdbc.Execution(Jdbc.ExecutionType.UPDATE)
    long deleteById(int id);
}
